
name: 'ny_311_service_requests'
version: '1.0.0'
profile: 'dbt_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ny_311_service_requests:
    staging:
      +materialized: table
      +partition_by:
        field: created_date
        data_type: timestamp
        granularity: day
      +cluster_by: ["problem", "borough"]
    intermediate:
      +materialized: table
    reporting:
      +materialized: table

seeds:
  ny_311_service_requests:
    +quote_columns: false
    ny_311_all_agencies_complaint_details:
      +delimiter: "|"
    ny_311_hpd_complaint_details:
      +delimiter: "|"


vars:
  # required by dbt_external_tables for BigQuery
  external_tables_batch_size: 10
  external_tables:
    render_using_jinja: true


dispatch:
  - macro_namespace: dbt_external_tables
    search_order: ['dbt_external_tables', 'dbt']